### ISSUE TITLE
请问那个分支是最新的

### ISSUE THREAD

**Issue by fuqiang03** [muink/luci-app-pcap-dnsproxy#1]
请问那个分支是最新的,好多分支看不明白哦 并且兼容master luci

**Comment by muink** [comment]
master 是最新稳定可用的 #7f2bd84姑且算是能用了, 主要的功能都有了
虽然28主项目那边已经被橄榄了, 这个项目处理完主要的功能也会停止更新吧
所以使用上如果遇到什么问题最好不要报太大的希望

**Comment by fuqiang03** [comment]
@muink 可否给个配置文件
![QQ截图20200722001629](https://user-images.githubusercontent.com/26851715/88079799-c6e80b00-cbb0-11ea-85e7-64b17d34200d.png)

**Comment by muink** [comment]
这个必选值是空的问题不影响的，是因为代理开关和DNSCurve开关关闭的原因，旗下的子参数都会被从uci配置中删除
但偏偏这部分参数有些是为不能为空的， 就会产生这种情况

可以检查以下高级设置里的系统配置文件，这个才能反应真实的配置情况

**Comment by fuqiang03** [comment]
@muink 
我有试了一下 不管服务是否运行 luci配置都会出错 配置文件也不会被删除或者修改 我怀疑应该是init下面的脚本问题可能和配置文件不匹配
还有请删除另一个分支 要不切换分支有些费劲
![QQ截图20200722155220](https://user-images.githubusercontent.com/26851715/88150841-7c0fd700-cc34-11ea-9179-751e6077c338.png)

**Comment by muink** [comment]
会弹出警告的涉及以下 UCI 配置项
> proxy_socks_ver
proxy_socks_proto
proxy_socks_ipv4_addr
proxy_socks_ipv6_addr
proxy_socks_tg_serv
proxy_http_proto
proxy_http_ipv4_addr
proxy_http_ipv6_addr
proxy_http_tg_serv
proxy_http_ver
dnscurve_proto
dnscurve_reliable_timeout
dnscurve_unreliable_timeout
dnscurve_key_recheck_time
dnscurve_serv_db_ipv4
dnscurve_serv_db_ipv6
dnscurve_serv_addr_ipv4
dnscurve_serv_addr_ipv4_prov
dnscurve_serv_addr_ipv4_pubkey
dnscurve_serv_addr_ipv6
dnscurve_serv_addr_ipv6_prov
dnscurve_serv_addr_ipv6_pubkey

原因是因为要展开以上参数，各自依赖以下开关 `proxy_http` `proxy_socks` `dnscurve`  
并且在它们各自所依赖的开关打开时这些配置项都是必填项，并且我希望我在关闭总开关后这些配置项依然能保留  
以便于我在下次重新打开开关时，LuCI 能够自动读取这些配置项而无需我重新输入一遍，于是我将其设为了不接受删除  

然而 LuCI 并没有像我预期的那样工作，默认 LuCI 会在进行保存时从 UCI 配置中移除依赖关系有效性为否的配置项  
于是它就傻乎乎地把这些依赖关系有效性为否但不接受删除的配置项给移除了，然后再傻乎乎地来给我一个报错  
这是设计逻辑上的冲突，所幸并不影响正常使用，下个版本我再处理下(因为我基本上都是在高级界面直接编辑 没怎么在意)  
如果介意的话可以编辑 `/usr/lib/lua/luci/model/cbi/pcap-dnsproxy/general.lua` 搜索这几个配置项  
将 `rmempty` 参数的值改为 **true** 后刷新页面或重启路由即可  

另外关于配置文件之前可能是我没解释清楚，真正控制程序运行的是位于 `/etc/pcap-dnsproxy/config.conf` 的运行时配置文件  
你需要点击 **应用到系统** 按钮才能把 UCI 配置真正应用到运行时配置文件，并且这个动作也只会提取有效的 UCI 配置  
所以你之前点保存确实配置文件是不会变动的

**Comment by fuqiang03** [comment]
好的 谢谢你

**Comment by fuqiang03** [comment]
发现列表一旦被隐藏了,luci就会删除对应的数据,

**Comment by muink** [comment]
> 发现列表一旦被隐藏了,luci就会删除对应的数据,

对的，就是这个意思

**Comment by fuqiang03** [comment]
@muink 
我以前也遇到过这个问题,但是我的是固定值
但是真要通过配置运行客户端的话绝对是个大工程
![QQ截图20200722234437](https://user-images.githubusercontent.com/26851715/88197795-8c947180-cc75-11ea-9af1-383d634e8154.png)
![QQ截图20200722234448](https://user-images.githubusercontent.com/26851715/88197806-9027f880-cc75-11ea-8569-c3a640fc200e.png)
